{% set name = "slim-trees" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 587385f0161cb343c03fb9f16f8236ae4cf684c804f03d2a208bf4f36030784b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1,<3
  run_constrained:
    - scikit-learn >=1.1,<1.6
    - lightgbm >=3.2,<4.4

test:
  imports:
    - slim_trees
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Quantco/slim-trees
  summary: A python package for efficient pickling of ML models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
