{% set name = "slim-trees" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8971a6eee87ac02e80bc4eb151ebc7b70a60a82cecaae59ab4c70349319a112c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy >=1,<3
  run_constrained:
    - scikit-learn >=1.1,<1.6
    - lightgbm >=3.2,<4.4

test:
  imports:
    - slim_trees
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quantco/slim-trees
  summary: A python package for efficient pickling of ML models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
