schema_version: 1

context:
  name: slim-trees
  version: 0.2.15

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 587385f0161cb343c03fb9f16f8236ae4cf684c804f03d2a208bf4f36030784b

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1,<3
  run_constraints:
    - scikit-learn >=1.1,<1.6
    - lightgbm >=3.3,<4.7

tests:
  - python:
      imports:
        - slim_trees
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: A python package for efficient pickling of ML models.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Quantco/slim-trees

extra:
  recipe-maintainers:
    - pavelzw
